package com.utomate.utomateTools;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

public class JavaFactory {
	private String mainClass;
	private String instructionsFile;
	private String dir;
	
	public JavaFactory(String dir) {
		this.dir = dir;
	}

	public void createProject(String fileName) {
		this.mainClass = this.dir + "/" + fileName + ".java";
	}
	
	public void createZip(String name) throws IOException {
        String zipFile = dir + "/" + name + ".zip";
		File[] filesToZip = {
        		new File(mainClass),
        		new File(instructionsFile)
        };
		FileOutputStream fos = new FileOutputStream(zipFile);
    	ZipOutputStream zos = new ZipOutputStream(fos);
    	
		for (File f : filesToZip) {
        	System.out.println("Zipping: " + f.getPath());
        	
        	// Stream
            FileInputStream fis = new FileInputStream(f);
            
            // Create file within ZIP
            ZipEntry zipEntry = new ZipEntry(f.getName());
            zos.putNextEntry(zipEntry);
            
            // Write content
            byte[] buffer = new byte[1024];
            int length;
            while ((length = fis.read(buffer)) >= 0) {
                zos.write(buffer, 0, length);
            }
            
            // Release memory
            zos.closeEntry();
            fis.close();
            System.out.println("File zipped: " + f.getPath());
        }
		
        zos.close();
        fos.close();
	}
	
	public void generateInstructions(String fileName) throws IOException {
		String template = "HOW TO RUN:\n\n"
				+ "1. Open command prompt in the project folder\n"
				+ "2. Run the following command: \"java %s.java\"\n"
				+ "\nTroubleshooting\n\n"
				+ "- Make sure you have the latest version of Java installed on your machine.\n"
				+ "- Make sure Java is configured in your system's PATH variables.\n";
		String text = String.format(template, fileName);
		File file = new File(dir + "/instructions.txt");
		FileWriter writer = new FileWriter(file);
		writer.write(text);
		writer.close();
		this.instructionsFile = file.getPath();
	}
	
	public void writeCode(AutomationAttributes attributes) throws IOException {
		String code = "" // Imports
				+ "public class Main {\n\tpublic static void main(String[] args){\n" // Run class & main() method declaration
				+ "\t\tSystem.out.println(\"This code was generated by Java!\");\n" // Initializations
				+ "\t}\n" // Ending brackets pt. 1
				+ "}"; // Ending brackets pt. 2
		FileWriter writer = new FileWriter(mainClass);
		writer.write(code);
		writer.close();
	}
}
