package com.utomate.utomateTools;

public class JavaFactory {
	private String code;
	
	public JavaFactory() {
		// Add default boilerblate
		this.setCode("" // Imports
				+ "public class Main {\n\tpublic static void main(String[] args){\n" // Run class & main() method declaration
				+ "\t\tSystem.out.println('This code was generated by Java!');\n" // Initializations
				+ "\t}\n" // Ending brackets pt. 1
				+ "}"); // Ending brackets pt. 2
		}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}
}
